services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Expose backend on port 5000
    environment:
      - FLASK_ENV=production  # Running in production mode
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map frontend port to 5000 (if you're serving static on port 5000)
    environment:
      - FRONTEND_ENV=production  # Set React app to production mode
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
    command: bash -c "npm install && chmod -R 777 /app/node_modules && npm start"
