

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - FRONTEND_ENV=development  # Set React app to development mode for hot-reloading
    volumes:
      - ./frontend:/app  # Sync the frontend code between your host and container
      - /app/node_modules  # Ensure node_modules doesn't get overwritten by the volume
    command: npm start 
  
